include:
  - ../_includes/head.html

title: "LDS"
description: "Comprehensive design system for Landcare groups."
remote_theme: just-the-docs/just-the-docs # Replace this with the theme you're using
baseurl: "/landcare-design-system" # Add the repository name
url: "https://landcare-groups.github.io/landcare-design-system/" # Your GitHub Pages URL